# Generated by Django 4.2.1 on 2023-05-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_server_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('clone_name', models.CharField(max_length=255)),
                ('clone_id', models.CharField(max_length=255)),
            ],
        ),
    ]
