# Generated by Django 4.2.1 on 2023-05-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_server_os'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server_os',
            options={'verbose_name_plural': 'server_os'},
        ),
        migrations.AlterModelOptions(
            name='server_packages',
            options={'verbose_name_plural': 'server_packages'},
        ),
    ]
