# Generated by Django 4.2.1 on 2023-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_alter_server_os_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_os',
            name='img_url',
            field=models.ImageField(null=True, upload_to='os/'),
        ),
    ]
