# Generated by Django 4.2.1 on 2023-05-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_server_os_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_os',
            name='img_url',
            field=models.ImageField(null=True, upload_to='static/images/os'),
        ),
    ]
