# Generated by Django 4.2.1 on 2023-05-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_server_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_ip', models.CharField(max_length=255)),
                ('server_os', models.CharField(max_length=255)),
                ('server_location', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.project')),
            ],
            options={
                'verbose_name_plural': 'servers',
            },
        ),
    ]
