# Generated by Django 4.2.1 on 2023-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='server_os_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
