# Generated by Django 4.2.1 on 2023-05-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0011_remove_servers_server_os_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servers',
            old_name='project_id',
            new_name='project',
        ),
    ]
