# Generated by Django 4.2.1 on 2023-05-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_rename_project_id_servers_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='server_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.server_packages'),
        ),
        migrations.AddField(
            model_name='servers',
            name='vm_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
